language: php

php:
  - 5.3
  - 5.4
  - 5.5

before_script:
  - echo '\n Installing Composer ..'
  - composer install --dev --no-interaction --prefer-source
  - echo '\n Configure PHP Unit ..'
  - cp phpunit.dist.xml phpunit.xml
  - phpunit --version
  - echo '\n Installing PEAR Packages ..'
  - pear config-set auto_discover 1
  - pear install pear.phing.info/phing
  - pear install pear.phpunit.de/phploc
  - pear install pear/PHP_CodeSniffer
  - pear install pear.pdepend.org/PHP_Depend

script: phpunit --coverage-text
